name: CI

on:
  push:
    branches:
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAT53XSAGRZ2ZLEPG5
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm test
    - run: mkdir dist
    - run: ls -l public
    - run: cp -R public dist
    - run: ls -l dist
    - name: build static
      run: npm run build-static
      env:
        NODE_ENV: development
    - run: ls -l dist

    - run: npm run upload-static
